In [1]:
import pandas as pd
import numpy as np
import scipy.stats as s
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
data.drop([data.columns[0],data.columns[32]],axis=1,inplace=True)

In [6]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
labels = np.array(data['diagnosis']).reshape(data['diagnosis'].shape[0],1)

In [8]:
X = np.array(data.iloc[:,1:])
X.shape

(569, 30)

In [9]:
mu = np.mean(X,axis=0)

In [10]:
mu.shape

(30,)

In [11]:
mu = mu.reshape(-1,mu.shape[0])

In [12]:
mu.shape

(1, 30)

In [13]:
X_dash = X - mu

In [14]:
X_dash.shape

(569, 30)

In [15]:
#covariance matrix
sigma_hat = (1/data.shape[0])*np.matmul(X_dash.T,X_dash)

In [16]:
sigma_hat.shape   #shape of cov matrix should be (30 x 30)

(30, 30)

In [17]:
# applying singular value decomposition on COV MATRIX

In [18]:
sigma_hat_decompose = np.linalg.svd(sigma_hat)

In [19]:
len(sigma_hat_decompose)

3

In [20]:
Q = sigma_hat_decompose[0]

In [21]:
lmbda = sigma_hat_decompose[1]

In [22]:
lmbda

array([4.43002671e+05, 7.29725279e+03, 7.02596776e+02, 5.45526944e+01,
       3.98199123e+01, 2.99930721e+00, 1.81213991e+00, 3.70813899e-01,
       1.55240237e-01, 8.39134846e-02, 3.15534015e-02, 7.48418875e-03,
       3.15610001e-03, 2.15770517e-03, 1.32420744e-03, 6.39144051e-04,
       3.74224474e-04, 2.34756323e-04, 1.84259067e-04, 1.63891523e-04,
       7.79729248e-05, 5.75099161e-05, 3.48559114e-05, 2.83453651e-05,
       1.61179909e-05, 1.24682907e-05, 3.67401338e-06, 2.84289915e-06,
       2.00139207e-06, 7.00763523e-07])

In [23]:
Q_tilda = Q[:,0:15]

In [24]:
Q_tilda.shape

(30, 15)

In [25]:
X_new = np.matmul(X_dash,Q_tilda)

In [26]:
X_new.shape

(569, 15)

In [27]:
new_data = pd.DataFrame(data=X_new)

In [28]:
new_data['diagnosis'] = labels

In [29]:
new_data.head()

0           1          2          3          4         5  \
0 -1160.142574 -293.917544  48.578398   8.711975  32.000486 -1.265415   
1 -1269.122443   15.630182 -35.394534 -17.861283  -4.334874  0.225872   
2  -995.793889   39.156743  -1.709753  -4.199340  -0.466529  2.652811   
3   407.180803  -67.380320   8.672848  11.759867   7.115461 -1.299436   
4  -930.341180  189.340742   1.374801  -8.499183   7.613289 -1.021160   

          6         7         8         9        10        11        12  \
0  0.931337 -0.148167 -0.745463  0.589359  0.307804 -0.043452  0.034777   
1 -0.046037 -0.200804  0.485828 -0.084035 -0.080642 -0.033042  0.045485   
2 -0.779745  0.274026  0.173874 -0.186994 -0.279174  0.020464  0.083505   
3 -1.267304  0.060555  0.330639 -0.144155 -0.927471  0.174720  0.282556   
4 -0.335522 -0.289109 -0.036087 -0.138502 -0.042228  0.062721 -0.114247   

         13        14 diagnosis  
0 -0.065069  0.012934         M  
1  0.005534 -0.021368         M  
2 -0.024824  0.026887         M  
3 -0.080057 -0.043201         M  
4 -0.002274  0.019548         M

In [30]:
new_data.shape

(569, 16)

In [31]:
new_data[new_data['diagnosis']=='B'].shape

(357, 16)

In [32]:
new_data[new_data['diagnosis']=='M'].shape

(212, 16)

In [33]:
training_data_len = int(0.7*data.shape[0])

In [34]:
training_data_len

398

In [35]:
benign_training_data = new_data[new_data['diagnosis']=='B'].iloc[0:training_data_len//2]
malignent_training_data = new_data[new_data['diagnosis']=='M'].iloc[0:training_data_len//2]

In [36]:
benign_training_data.shape

(199, 16)

In [37]:
malignent_training_data.shape

(199, 16)

In [38]:
training_data = pd.concat([benign_training_data,malignent_training_data])

In [39]:
training_data.shape

(398, 16)

In [40]:
training_data

0           1          2          3         4         5  \
19    191.621045   12.259178  -6.241020  -3.588034  6.692721  0.037497   
20    285.051275   14.557362 -10.177971  -1.483015  5.828780  0.790474   
21    683.583952  -32.576126  15.095343 -12.576780  1.707262 -1.104473   
37    355.877850   61.535566  -6.242785  -4.970090 -3.076071  1.750950   
46    783.838668  -56.826556  13.657869 -10.929661 -7.112941 -2.742609   
..           ...         ...        ...        ...       ...       ...   
499 -1099.486889  112.597421 -27.476067  -0.145937 -2.458353 -1.537728   
501   109.464701   -2.229269   3.854344  10.871600 -3.023712  2.215435   
503 -2166.185165 -108.422615  21.170655  -9.870265  4.600230 -6.029129   
509   -64.596512   50.650874 -13.205191  13.519044 -3.370923  1.640083   
512    81.753871  -65.157008  -2.878240  10.121694  4.231035 -1.561071   

            6         7         8         9        10        11        12  \
19   0.336992  0.159502 -0.013716  0.010386  0.078203 -0.036511 -0.029271   
20   0.080541  0.454472 -0.268240  0.092501  0.032368  0.122332  0.037006   
21  -0.309995 -0.328012 -0.135464 -0.232627 -0.039800  0.013665 -0.016789   
37  -0.091251 -0.511769 -0.102631  1.011803  0.024114 -0.059378 -0.000325   
46  -0.747497  0.247352 -0.345514 -0.233113 -0.080757  0.095598  0.009075   
..        ...       ...       ...       ...       ...       ...       ...   
499  1.274740 -0.224613 -0.469098 -0.102762  0.047910  0.093248 -0.100222   
501  0.365275  0.020654 -0.201790 -0.171657 -0.100881  0.175142  0.032250   
503 -3.231749 -0.385159  0.459618  0.086349  0.186573 -0.070107  0.065125   
509  2.685771 -0.600741 -0.693918 -0.225630  0.032308 -0.042296 -0.018556   
512  0.335364  0.303605 -0.151272 -0.183464  0.011138 -0.013619 -0.058982   

           13        14 diagnosis  
19  -0.039346 -0.017123         B  
20   0.000394 -0.017677         B  
21   0.007654  0.010671         B  
37   0.018064 -0.035210         B  
46  -0.027129 -0.006755         B  
..        ...       ...       ...  
499  0.029009  0.056247         M  
501 -0.029611  0.042311         M  
503  0.036807  0.019955         M  
509  0.033451  0.003069         M  
512 -0.046188  0.004539         M  

[398 rows x 16 columns]

In [41]:
cv_data_len = int(0.2*data.shape[0])

In [42]:
cv_data_len

113

In [43]:
benign_remaining_data = new_data[new_data['diagnosis'] == 'B'].iloc[training_data_len//2:]
malignent_remaining_data =  new_data[new_data['diagnosis'] == 'M'].iloc[training_data_len//2:]

In [44]:
benign_remaining_data.shape

(158, 16)

In [45]:
malignent_remaining_data.shape

(13, 16)

In [46]:
remaining_data = pd.concat([benign_remaining_data,malignent_remaining_data])

In [47]:
remaining_data.shape

(171, 16)

In [48]:
cv_data = remaining_data.iloc[0:cv_data_len]
testing_data = remaining_data.iloc[cv_data_len:]

In [49]:
cv_data.shape

(113, 16)

In [50]:
testing_data.shape

(58, 16)

So now we need to evaluate the following probability:

\begin{equation}
P(Diagnosis = M | radius mean = x) = P(radius mean = x | Diagnosis  M) P(texture mean = y | Diagnosis = M) P(Diagnosis = M)
\end{equation}

Now, in order to evaluate the likelihood probability P(radius mean = X | Diagnosis = M) P(texture mean = y | Diagnosis = M) which is given by **Multivariate Joint Gausssian Distribution PDF**.
Now for this PDF, we need to find out the best estimate of the parameters of **Multivariate joint Normal Distribution** because we are assuming that our Malignent tumor training data is being sampled from a multivariate Joint Normal (Gaussian) Distribution. The two parameters will be namely: **mu_hat_m and sigma_hat_m**

In [51]:
mu_hat_m = np.array(training_data[training_data['diagnosis'] == 'M'].iloc[:,0:15].mean())

sigma_hat_m = np.array(training_data[training_data['diagnosis'] == 'M'].iloc[:,0:15].cov())

In [52]:
mu_hat_m

array([-6.19149059e+02, -9.10604406e+00, -3.00251408e+00,  3.21867937e+00,
        6.62722209e-01, -1.49641755e-03,  1.33728677e-01, -6.56051800e-03,
        4.44266350e-02, -2.27845949e-02, -5.28254216e-02,  2.13821710e-03,
        2.13592658e-03, -4.87610367e-03,  1.12627757e-04])

In [53]:
np.linalg.det(sigma_hat_m)

19723.271206451547

In [54]:
sigma_hat_m.diagonal()

array([4.83251406e+05, 1.80244546e+04, 1.71425537e+03, 7.92821249e+01,
       4.99687724e+01, 4.96625902e+00, 2.33253962e+00, 5.72687305e-01,
       3.00085039e-01, 8.46220743e-02, 4.76165511e-02, 1.09368344e-02,
       5.88573773e-03, 3.24464641e-03, 2.37829604e-03])

In [55]:
sigma_hat_m.shape

(15, 15)

In [56]:
malignent_prior = training_data[training_data['diagnosis'] == 'M'].shape[0]/training_data.shape[0]

So now we need to evaluate the following probability:

\begin{equation}
P(Diagnosis = B | radius mean = x) = P(radius mean = x | Diagnosis  B) P(texture mean = y | Diagnosis = B) P(Diagnosis = B)
\end{equation}

Now, in order to evaluate the likelihood probability P(radius mean = X | Diagnosis = B) P(texture mean = y | Diagnosis = B) which is given by **Multivariate Joint Gausssian Distribution PDF**.
Now for this PDF, we need to find out the best estimate of the parameters of **Multivariate joint Normal Distribution** because we are assuming that our benign tumor training data is being sampled from a multivariate Joint Normal (Gaussian) Distribution. The two parameters will be namely: **mu_hat_b and sigma_hat_b**

In [57]:
mu_hat_b = np.array(training_data[training_data['diagnosis'] == 'B'].iloc[:,0:15].mean())

sigma_hat_b = np.array(training_data[training_data['diagnosis'] == 'B'].iloc[:,0:15].cov())

In [58]:
mu_hat_b

array([ 3.97528379e+02,  9.06204470e-01,  3.54739985e+00, -3.13352427e+00,
        3.79908894e-01,  4.33533255e-02, -2.13645508e-02, -4.14581153e-02,
       -1.31463250e-02,  1.36211788e-02,  2.10626089e-02, -1.23645051e-03,
       -1.94878048e-03, -1.52977374e-03,  1.01138045e-03])

In [59]:
np.linalg.det(sigma_hat_b)

1.8304458896877537e-06

In [60]:
sigma_hat_b.shape

(15, 15)

In [61]:
sigma_hat_b.diagonal()

array([3.93448586e+04, 1.18379962e+03, 1.40075464e+02, 2.47387277e+01,
       2.65583990e+01, 1.70909441e+00, 1.36650566e+00, 2.70243150e-01,
       6.55623830e-02, 9.32803276e-02, 2.61349867e-02, 6.33739713e-03,
       2.01105944e-03, 1.86785462e-03, 8.75868974e-04])

In [62]:
benign_prior = training_data[training_data['diagnosis'] == 'B'].shape[0]/training_data.shape[0]

In [65]:
def mock_test(data):
  
  inputs = np.array(data.iloc[:,0:15])

  posterior_m = s.multivariate_normal.pdf(inputs,mu_hat_m,sigma_hat_m) * malignent_prior

  posterior_b = s.multivariate_normal.pdf(inputs,mu_hat_b,sigma_hat_b) * benign_prior

  boolean_mask = posterior_m > posterior_b
  
  predicted_category = pd.Series(boolean_mask)

  predicted_category.replace(to_replace=[False,True],value=['B','M'],inplace=True)
  
  return np.array(predicted_category)

In [66]:
cv_results = mock_test(cv_data)

In [67]:
actual_results = np.array(cv_data['diagnosis'])

In [68]:
boolean_mask = cv_results == actual_results

In [69]:
boolean_mask

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [70]:
cv_accuracy = np.count_nonzero(boolean_mask)/boolean_mask.shape[0]

In [71]:
cv_accuracy

0.9292035398230089

In [72]:
testing_results = mock_test(testing_data)

In [73]:
testing_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'B',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [74]:
actual_results = np.array(testing_data['diagnosis'])

In [75]:
actual_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [76]:
testing_accuracy = np.count_nonzero(testing_results == actual_results)/actual_results.shape[0]

In [77]:
testing_accuracy

0.9827586206896551